//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClientTest.BLService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BLService")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ConsoleClientTest.BLService.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleClientTest.BLService.Shop ShopField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShopIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ConsoleClientTest.BLService.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleClientTest.BLService.Shop Shop {
            get {
                return this.ShopField;
            }
            set {
                if ((object.ReferenceEquals(this.ShopField, value) != true)) {
                    this.ShopField = value;
                    this.RaisePropertyChanged("Shop");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop", Namespace="http://schemas.datacontract.org/2004/07/BLService")]
    [System.SerializableAttribute()]
    public partial class Shop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/BLService")]
    public enum Category : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MEAT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEGETABLES_FRUITS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DAIRY = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DRINKS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALCOHOL = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BREAD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWEETS = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTHER = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNRECOGNIZED = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLService.IBLService")]
    public interface IBLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/GetPrices", ReplyAction="http://tempuri.org/IBLService/GetPricesResponse")]
        System.Collections.Generic.List<ConsoleClientTest.BLService.Product> GetPrices(byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/GetPrices", ReplyAction="http://tempuri.org/IBLService/GetPricesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Product>> GetPricesAsync(byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/GetShops", ReplyAction="http://tempuri.org/IBLService/GetShopsResponse")]
        System.Collections.Generic.List<ConsoleClientTest.BLService.Shop> GetShops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/GetShops", ReplyAction="http://tempuri.org/IBLService/GetShopsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Shop>> GetShopsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/Post", ReplyAction="http://tempuri.org/IBLService/PostResponse")]
        System.Collections.Generic.List<ConsoleClientTest.BLService.Product> Post(ConsoleClientTest.BLService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/Post", ReplyAction="http://tempuri.org/IBLService/PostResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Product>> PostAsync(ConsoleClientTest.BLService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/Test", ReplyAction="http://tempuri.org/IBLService/TestResponse")]
        string Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/Test", ReplyAction="http://tempuri.org/IBLService/TestResponse")]
        System.Threading.Tasks.Task<string> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/Search", ReplyAction="http://tempuri.org/IBLService/SearchResponse")]
        System.Collections.Generic.List<ConsoleClientTest.BLService.Product> Search(ConsoleClientTest.BLService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/Search", ReplyAction="http://tempuri.org/IBLService/SearchResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Product>> SearchAsync(ConsoleClientTest.BLService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/InsertProduct", ReplyAction="http://tempuri.org/IBLService/InsertProductResponse")]
        int InsertProduct(ConsoleClientTest.BLService.Product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/InsertProduct", ReplyAction="http://tempuri.org/IBLService/InsertProductResponse")]
        System.Threading.Tasks.Task<int> InsertProductAsync(ConsoleClientTest.BLService.Product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/UpdateProduct", ReplyAction="http://tempuri.org/IBLService/UpdateProductResponse")]
        int UpdateProduct(ConsoleClientTest.BLService.Product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/UpdateProduct", ReplyAction="http://tempuri.org/IBLService/UpdateProductResponse")]
        System.Threading.Tasks.Task<int> UpdateProductAsync(ConsoleClientTest.BLService.Product p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/InsertShop", ReplyAction="http://tempuri.org/IBLService/InsertShopResponse")]
        int InsertShop(ConsoleClientTest.BLService.Shop s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/InsertShop", ReplyAction="http://tempuri.org/IBLService/InsertShopResponse")]
        System.Threading.Tasks.Task<int> InsertShopAsync(ConsoleClientTest.BLService.Shop s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/DeleteShop", ReplyAction="http://tempuri.org/IBLService/DeleteShopResponse")]
        int DeleteShop(ConsoleClientTest.BLService.Shop s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBLService/DeleteShop", ReplyAction="http://tempuri.org/IBLService/DeleteShopResponse")]
        System.Threading.Tasks.Task<int> DeleteShopAsync(ConsoleClientTest.BLService.Shop s);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBLServiceChannel : ConsoleClientTest.BLService.IBLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLServiceClient : System.ServiceModel.ClientBase<ConsoleClientTest.BLService.IBLService>, ConsoleClientTest.BLService.IBLService {
        
        public BLServiceClient() {
        }
        
        public BLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ConsoleClientTest.BLService.Product> GetPrices(byte[] image) {
            return base.Channel.GetPrices(image);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Product>> GetPricesAsync(byte[] image) {
            return base.Channel.GetPricesAsync(image);
        }
        
        public System.Collections.Generic.List<ConsoleClientTest.BLService.Shop> GetShops() {
            return base.Channel.GetShops();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Shop>> GetShopsAsync() {
            return base.Channel.GetShopsAsync();
        }
        
        public System.Collections.Generic.List<ConsoleClientTest.BLService.Product> Post(ConsoleClientTest.BLService.Product product) {
            return base.Channel.Post(product);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Product>> PostAsync(ConsoleClientTest.BLService.Product product) {
            return base.Channel.PostAsync(product);
        }
        
        public string Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<string> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public System.Collections.Generic.List<ConsoleClientTest.BLService.Product> Search(ConsoleClientTest.BLService.Product product) {
            return base.Channel.Search(product);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsoleClientTest.BLService.Product>> SearchAsync(ConsoleClientTest.BLService.Product product) {
            return base.Channel.SearchAsync(product);
        }
        
        public int InsertProduct(ConsoleClientTest.BLService.Product p) {
            return base.Channel.InsertProduct(p);
        }
        
        public System.Threading.Tasks.Task<int> InsertProductAsync(ConsoleClientTest.BLService.Product p) {
            return base.Channel.InsertProductAsync(p);
        }
        
        public int UpdateProduct(ConsoleClientTest.BLService.Product p) {
            return base.Channel.UpdateProduct(p);
        }
        
        public System.Threading.Tasks.Task<int> UpdateProductAsync(ConsoleClientTest.BLService.Product p) {
            return base.Channel.UpdateProductAsync(p);
        }
        
        public int InsertShop(ConsoleClientTest.BLService.Shop s) {
            return base.Channel.InsertShop(s);
        }
        
        public System.Threading.Tasks.Task<int> InsertShopAsync(ConsoleClientTest.BLService.Shop s) {
            return base.Channel.InsertShopAsync(s);
        }
        
        public int DeleteShop(ConsoleClientTest.BLService.Shop s) {
            return base.Channel.DeleteShop(s);
        }
        
        public System.Threading.Tasks.Task<int> DeleteShopAsync(ConsoleClientTest.BLService.Shop s) {
            return base.Channel.DeleteShopAsync(s);
        }
    }
}
