//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApp.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BLService")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string NameField;
        
        private string PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop", Namespace="http://schemas.datacontract.org/2004/07/BLService")]
    public partial class Shop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBLService")]
    public interface IBLService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/GetPrices", ReplyAction="http://tempuri.org/IBLService/GetPricesResponse")]
        System.IAsyncResult BeginGetPrices(byte[] image, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<MobileApp.ServiceReference1.Product> EndGetPrices(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/GetShops", ReplyAction="http://tempuri.org/IBLService/GetShopsResponse")]
        System.IAsyncResult BeginGetShops(System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<MobileApp.ServiceReference1.Shop> EndGetShops(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/GetString", ReplyAction="http://tempuri.org/IBLService/GetStringResponse")]
        System.IAsyncResult BeginGetString(System.AsyncCallback callback, object asyncState);
        
        string EndGetString(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/Search", ReplyAction="http://tempuri.org/IBLService/SearchResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<MobileApp.ServiceReference1.Product>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MobileApp.ServiceReference1.Product))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<MobileApp.ServiceReference1.Shop>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MobileApp.ServiceReference1.Shop))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        System.IAsyncResult BeginSearch(string itemName, System.Collections.Generic.List<object> itemList, System.AsyncCallback callback, object asyncState);
        
        System.Collections.Generic.List<MobileApp.ServiceReference1.Product> EndSearch(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBLServiceChannel : MobileApp.ServiceReference1.IBLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<MobileApp.ServiceReference1.Product> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<MobileApp.ServiceReference1.Product>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetShopsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetShopsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<MobileApp.ServiceReference1.Shop> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<MobileApp.ServiceReference1.Shop>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.Generic.List<MobileApp.ServiceReference1.Product> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.Generic.List<MobileApp.ServiceReference1.Product>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLServiceClient : System.ServiceModel.ClientBase<MobileApp.ServiceReference1.IBLService>, MobileApp.ServiceReference1.IBLService {
        
        private BeginOperationDelegate onBeginGetPricesDelegate;
        
        private EndOperationDelegate onEndGetPricesDelegate;
        
        private System.Threading.SendOrPostCallback onGetPricesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetShopsDelegate;
        
        private EndOperationDelegate onEndGetShopsDelegate;
        
        private System.Threading.SendOrPostCallback onGetShopsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStringDelegate;
        
        private EndOperationDelegate onEndGetStringDelegate;
        
        private System.Threading.SendOrPostCallback onGetStringCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public BLServiceClient() : 
                base(BLServiceClient.GetDefaultBinding(), BLServiceClient.GetDefaultEndpointAddress()) {
        }
        
        public BLServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BLServiceClient.GetBindingForEndpoint(endpointConfiguration), BLServiceClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public BLServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BLServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public BLServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BLServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public BLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetPricesCompletedEventArgs> GetPricesCompleted;
        
        public event System.EventHandler<GetShopsCompletedEventArgs> GetShopsCompleted;
        
        public event System.EventHandler<GetStringCompletedEventArgs> GetStringCompleted;
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.ServiceReference1.IBLService.BeginGetPrices(byte[] image, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPrices(image, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<MobileApp.ServiceReference1.Product> MobileApp.ServiceReference1.IBLService.EndGetPrices(System.IAsyncResult result) {
            return base.Channel.EndGetPrices(result);
        }
        
        private System.IAsyncResult OnBeginGetPrices(object[] inValues, System.AsyncCallback callback, object asyncState) {
            byte[] image = ((byte[])(inValues[0]));
            return ((MobileApp.ServiceReference1.IBLService)(this)).BeginGetPrices(image, callback, asyncState);
        }
        
        private object[] OnEndGetPrices(System.IAsyncResult result) {
            System.Collections.Generic.List<MobileApp.ServiceReference1.Product> retVal = ((MobileApp.ServiceReference1.IBLService)(this)).EndGetPrices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPricesCompleted(object state) {
            if ((this.GetPricesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPricesCompleted(this, new GetPricesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPricesAsync(byte[] image) {
            this.GetPricesAsync(image, null);
        }
        
        public void GetPricesAsync(byte[] image, object userState) {
            if ((this.onBeginGetPricesDelegate == null)) {
                this.onBeginGetPricesDelegate = new BeginOperationDelegate(this.OnBeginGetPrices);
            }
            if ((this.onEndGetPricesDelegate == null)) {
                this.onEndGetPricesDelegate = new EndOperationDelegate(this.OnEndGetPrices);
            }
            if ((this.onGetPricesCompletedDelegate == null)) {
                this.onGetPricesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPricesCompleted);
            }
            base.InvokeAsync(this.onBeginGetPricesDelegate, new object[] {
                        image}, this.onEndGetPricesDelegate, this.onGetPricesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.ServiceReference1.IBLService.BeginGetShops(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetShops(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<MobileApp.ServiceReference1.Shop> MobileApp.ServiceReference1.IBLService.EndGetShops(System.IAsyncResult result) {
            return base.Channel.EndGetShops(result);
        }
        
        private System.IAsyncResult OnBeginGetShops(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MobileApp.ServiceReference1.IBLService)(this)).BeginGetShops(callback, asyncState);
        }
        
        private object[] OnEndGetShops(System.IAsyncResult result) {
            System.Collections.Generic.List<MobileApp.ServiceReference1.Shop> retVal = ((MobileApp.ServiceReference1.IBLService)(this)).EndGetShops(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetShopsCompleted(object state) {
            if ((this.GetShopsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetShopsCompleted(this, new GetShopsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetShopsAsync() {
            this.GetShopsAsync(null);
        }
        
        public void GetShopsAsync(object userState) {
            if ((this.onBeginGetShopsDelegate == null)) {
                this.onBeginGetShopsDelegate = new BeginOperationDelegate(this.OnBeginGetShops);
            }
            if ((this.onEndGetShopsDelegate == null)) {
                this.onEndGetShopsDelegate = new EndOperationDelegate(this.OnEndGetShops);
            }
            if ((this.onGetShopsCompletedDelegate == null)) {
                this.onGetShopsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetShopsCompleted);
            }
            base.InvokeAsync(this.onBeginGetShopsDelegate, null, this.onEndGetShopsDelegate, this.onGetShopsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.ServiceReference1.IBLService.BeginGetString(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetString(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string MobileApp.ServiceReference1.IBLService.EndGetString(System.IAsyncResult result) {
            return base.Channel.EndGetString(result);
        }
        
        private System.IAsyncResult OnBeginGetString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MobileApp.ServiceReference1.IBLService)(this)).BeginGetString(callback, asyncState);
        }
        
        private object[] OnEndGetString(System.IAsyncResult result) {
            string retVal = ((MobileApp.ServiceReference1.IBLService)(this)).EndGetString(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStringCompleted(object state) {
            if ((this.GetStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStringCompleted(this, new GetStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStringAsync() {
            this.GetStringAsync(null);
        }
        
        public void GetStringAsync(object userState) {
            if ((this.onBeginGetStringDelegate == null)) {
                this.onBeginGetStringDelegate = new BeginOperationDelegate(this.OnBeginGetString);
            }
            if ((this.onEndGetStringDelegate == null)) {
                this.onEndGetStringDelegate = new EndOperationDelegate(this.OnEndGetString);
            }
            if ((this.onGetStringCompletedDelegate == null)) {
                this.onGetStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStringCompleted);
            }
            base.InvokeAsync(this.onBeginGetStringDelegate, null, this.onEndGetStringDelegate, this.onGetStringCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.ServiceReference1.IBLService.BeginSearch(string itemName, System.Collections.Generic.List<object> itemList, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(itemName, itemList, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.Generic.List<MobileApp.ServiceReference1.Product> MobileApp.ServiceReference1.IBLService.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string itemName = ((string)(inValues[0]));
            System.Collections.Generic.List<object> itemList = ((System.Collections.Generic.List<object>)(inValues[1]));
            return ((MobileApp.ServiceReference1.IBLService)(this)).BeginSearch(itemName, itemList, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            System.Collections.Generic.List<MobileApp.ServiceReference1.Product> retVal = ((MobileApp.ServiceReference1.IBLService)(this)).EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(string itemName, System.Collections.Generic.List<object> itemList) {
            this.SearchAsync(itemName, itemList, null);
        }
        
        public void SearchAsync(string itemName, System.Collections.Generic.List<object> itemList, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        itemName,
                        itemList}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MobileApp.ServiceReference1.IBLService CreateChannel() {
            return new BLServiceClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBLService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBLService)) {
                return new System.ServiceModel.EndpointAddress("http://desktop-iu70sn1/BLService/BLService.svc/BLService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return BLServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBLService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return BLServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBLService);
        }
        
        private class BLServiceClientChannel : ChannelBase<MobileApp.ServiceReference1.IBLService>, MobileApp.ServiceReference1.IBLService {
            
            public BLServiceClientChannel(System.ServiceModel.ClientBase<MobileApp.ServiceReference1.IBLService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPrices(byte[] image, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = image;
                System.IAsyncResult _result = base.BeginInvoke("GetPrices", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<MobileApp.ServiceReference1.Product> EndGetPrices(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<MobileApp.ServiceReference1.Product> _result = ((System.Collections.Generic.List<MobileApp.ServiceReference1.Product>)(base.EndInvoke("GetPrices", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetShops(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetShops", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<MobileApp.ServiceReference1.Shop> EndGetShops(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<MobileApp.ServiceReference1.Shop> _result = ((System.Collections.Generic.List<MobileApp.ServiceReference1.Shop>)(base.EndInvoke("GetShops", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetString(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetString", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetString(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetString", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearch(string itemName, System.Collections.Generic.List<object> itemList, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = itemName;
                _args[1] = itemList;
                System.IAsyncResult _result = base.BeginInvoke("Search", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.Generic.List<MobileApp.ServiceReference1.Product> EndSearch(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.Generic.List<MobileApp.ServiceReference1.Product> _result = ((System.Collections.Generic.List<MobileApp.ServiceReference1.Product>)(base.EndInvoke("Search", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IBLService,
        }
    }
}
