//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileApp.BLService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/BLService")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CategoryField;
        
        private System.DateTime DateField;
        
        private string NameField;
        
        private string PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Price {
            get {
                return this.PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceField, value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop", Namespace="http://schemas.datacontract.org/2004/07/BLService")]
    public partial class Shop : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long IdField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BLService.IBLService")]
    public interface IBLService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/GetPrices", ReplyAction="http://tempuri.org/IBLService/GetPricesResponse")]
        System.IAsyncResult BeginGetPrices(byte[] image, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> EndGetPrices(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/GetShops", ReplyAction="http://tempuri.org/IBLService/GetShopsResponse")]
        System.IAsyncResult BeginGetShops(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop> EndGetShops(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/Post", ReplyAction="http://tempuri.org/IBLService/PostResponse")]
        System.IAsyncResult BeginPost(System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> products, MobileApp.BLService.Shop shop, System.AsyncCallback callback, object asyncState);
        
        void EndPost(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/Test", ReplyAction="http://tempuri.org/IBLService/TestResponse")]
        System.IAsyncResult BeginTest(System.AsyncCallback callback, object asyncState);
        
        string EndTest(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IBLService/Search", ReplyAction="http://tempuri.org/IBLService/SearchResponse")]
        System.IAsyncResult BeginSearch(string itemName, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> EndSearch(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBLServiceChannel : MobileApp.BLService.IBLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPricesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPricesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetShopsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetShopsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BLServiceClient : System.ServiceModel.ClientBase<MobileApp.BLService.IBLService>, MobileApp.BLService.IBLService {
        
        private BeginOperationDelegate onBeginGetPricesDelegate;
        
        private EndOperationDelegate onEndGetPricesDelegate;
        
        private System.Threading.SendOrPostCallback onGetPricesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetShopsDelegate;
        
        private EndOperationDelegate onEndGetShopsDelegate;
        
        private System.Threading.SendOrPostCallback onGetShopsCompletedDelegate;
        
        private BeginOperationDelegate onBeginPostDelegate;
        
        private EndOperationDelegate onEndPostDelegate;
        
        private System.Threading.SendOrPostCallback onPostCompletedDelegate;
        
        private BeginOperationDelegate onBeginTestDelegate;
        
        private EndOperationDelegate onEndTestDelegate;
        
        private System.Threading.SendOrPostCallback onTestCompletedDelegate;
        
        private BeginOperationDelegate onBeginSearchDelegate;
        
        private EndOperationDelegate onEndSearchDelegate;
        
        private System.Threading.SendOrPostCallback onSearchCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public BLServiceClient() : 
                base(BLServiceClient.GetDefaultBinding(), BLServiceClient.GetDefaultEndpointAddress()) {
        }
        
        public BLServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(BLServiceClient.GetBindingForEndpoint(endpointConfiguration), BLServiceClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public BLServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BLServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public BLServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BLServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public BLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetPricesCompletedEventArgs> GetPricesCompleted;
        
        public event System.EventHandler<GetShopsCompletedEventArgs> GetShopsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> PostCompleted;
        
        public event System.EventHandler<TestCompletedEventArgs> TestCompleted;
        
        public event System.EventHandler<SearchCompletedEventArgs> SearchCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.BLService.IBLService.BeginGetPrices(byte[] image, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPrices(image, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> MobileApp.BLService.IBLService.EndGetPrices(System.IAsyncResult result) {
            return base.Channel.EndGetPrices(result);
        }
        
        private System.IAsyncResult OnBeginGetPrices(object[] inValues, System.AsyncCallback callback, object asyncState) {
            byte[] image = ((byte[])(inValues[0]));
            return ((MobileApp.BLService.IBLService)(this)).BeginGetPrices(image, callback, asyncState);
        }
        
        private object[] OnEndGetPrices(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> retVal = ((MobileApp.BLService.IBLService)(this)).EndGetPrices(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPricesCompleted(object state) {
            if ((this.GetPricesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPricesCompleted(this, new GetPricesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPricesAsync(byte[] image) {
            this.GetPricesAsync(image, null);
        }
        
        public void GetPricesAsync(byte[] image, object userState) {
            if ((this.onBeginGetPricesDelegate == null)) {
                this.onBeginGetPricesDelegate = new BeginOperationDelegate(this.OnBeginGetPrices);
            }
            if ((this.onEndGetPricesDelegate == null)) {
                this.onEndGetPricesDelegate = new EndOperationDelegate(this.OnEndGetPrices);
            }
            if ((this.onGetPricesCompletedDelegate == null)) {
                this.onGetPricesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPricesCompleted);
            }
            base.InvokeAsync(this.onBeginGetPricesDelegate, new object[] {
                        image}, this.onEndGetPricesDelegate, this.onGetPricesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.BLService.IBLService.BeginGetShops(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetShops(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop> MobileApp.BLService.IBLService.EndGetShops(System.IAsyncResult result) {
            return base.Channel.EndGetShops(result);
        }
        
        private System.IAsyncResult OnBeginGetShops(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MobileApp.BLService.IBLService)(this)).BeginGetShops(callback, asyncState);
        }
        
        private object[] OnEndGetShops(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop> retVal = ((MobileApp.BLService.IBLService)(this)).EndGetShops(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetShopsCompleted(object state) {
            if ((this.GetShopsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetShopsCompleted(this, new GetShopsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetShopsAsync() {
            this.GetShopsAsync(null);
        }
        
        public void GetShopsAsync(object userState) {
            if ((this.onBeginGetShopsDelegate == null)) {
                this.onBeginGetShopsDelegate = new BeginOperationDelegate(this.OnBeginGetShops);
            }
            if ((this.onEndGetShopsDelegate == null)) {
                this.onEndGetShopsDelegate = new EndOperationDelegate(this.OnEndGetShops);
            }
            if ((this.onGetShopsCompletedDelegate == null)) {
                this.onGetShopsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetShopsCompleted);
            }
            base.InvokeAsync(this.onBeginGetShopsDelegate, null, this.onEndGetShopsDelegate, this.onGetShopsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.BLService.IBLService.BeginPost(System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> products, MobileApp.BLService.Shop shop, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginPost(products, shop, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void MobileApp.BLService.IBLService.EndPost(System.IAsyncResult result) {
            base.Channel.EndPost(result);
        }
        
        private System.IAsyncResult OnBeginPost(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> products = ((System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product>)(inValues[0]));
            MobileApp.BLService.Shop shop = ((MobileApp.BLService.Shop)(inValues[1]));
            return ((MobileApp.BLService.IBLService)(this)).BeginPost(products, shop, callback, asyncState);
        }
        
        private object[] OnEndPost(System.IAsyncResult result) {
            ((MobileApp.BLService.IBLService)(this)).EndPost(result);
            return null;
        }
        
        private void OnPostCompleted(object state) {
            if ((this.PostCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void PostAsync(System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> products, MobileApp.BLService.Shop shop) {
            this.PostAsync(products, shop, null);
        }
        
        public void PostAsync(System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> products, MobileApp.BLService.Shop shop, object userState) {
            if ((this.onBeginPostDelegate == null)) {
                this.onBeginPostDelegate = new BeginOperationDelegate(this.OnBeginPost);
            }
            if ((this.onEndPostDelegate == null)) {
                this.onEndPostDelegate = new EndOperationDelegate(this.OnEndPost);
            }
            if ((this.onPostCompletedDelegate == null)) {
                this.onPostCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostCompleted);
            }
            base.InvokeAsync(this.onBeginPostDelegate, new object[] {
                        products,
                        shop}, this.onEndPostDelegate, this.onPostCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.BLService.IBLService.BeginTest(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginTest(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string MobileApp.BLService.IBLService.EndTest(System.IAsyncResult result) {
            return base.Channel.EndTest(result);
        }
        
        private System.IAsyncResult OnBeginTest(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((MobileApp.BLService.IBLService)(this)).BeginTest(callback, asyncState);
        }
        
        private object[] OnEndTest(System.IAsyncResult result) {
            string retVal = ((MobileApp.BLService.IBLService)(this)).EndTest(result);
            return new object[] {
                    retVal};
        }
        
        private void OnTestCompleted(object state) {
            if ((this.TestCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.TestCompleted(this, new TestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        public void TestAsync(object userState) {
            if ((this.onBeginTestDelegate == null)) {
                this.onBeginTestDelegate = new BeginOperationDelegate(this.OnBeginTest);
            }
            if ((this.onEndTestDelegate == null)) {
                this.onEndTestDelegate = new EndOperationDelegate(this.OnEndTest);
            }
            if ((this.onTestCompletedDelegate == null)) {
                this.onTestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnTestCompleted);
            }
            base.InvokeAsync(this.onBeginTestDelegate, null, this.onEndTestDelegate, this.onTestCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MobileApp.BLService.IBLService.BeginSearch(string itemName, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSearch(itemName, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> MobileApp.BLService.IBLService.EndSearch(System.IAsyncResult result) {
            return base.Channel.EndSearch(result);
        }
        
        private System.IAsyncResult OnBeginSearch(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string itemName = ((string)(inValues[0]));
            return ((MobileApp.BLService.IBLService)(this)).BeginSearch(itemName, callback, asyncState);
        }
        
        private object[] OnEndSearch(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> retVal = ((MobileApp.BLService.IBLService)(this)).EndSearch(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSearchCompleted(object state) {
            if ((this.SearchCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SearchCompleted(this, new SearchCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SearchAsync(string itemName) {
            this.SearchAsync(itemName, null);
        }
        
        public void SearchAsync(string itemName, object userState) {
            if ((this.onBeginSearchDelegate == null)) {
                this.onBeginSearchDelegate = new BeginOperationDelegate(this.OnBeginSearch);
            }
            if ((this.onEndSearchDelegate == null)) {
                this.onEndSearchDelegate = new EndOperationDelegate(this.OnEndSearch);
            }
            if ((this.onSearchCompletedDelegate == null)) {
                this.onSearchCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSearchCompleted);
            }
            base.InvokeAsync(this.onBeginSearchDelegate, new object[] {
                        itemName}, this.onEndSearchDelegate, this.onSearchCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MobileApp.BLService.IBLService CreateChannel() {
            return new BLServiceClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBLService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IBLService)) {
                return new System.ServiceModel.EndpointAddress("http://horse/BLService/BLService.svc/BLService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return BLServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IBLService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return BLServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IBLService);
        }
        
        private class BLServiceClientChannel : ChannelBase<MobileApp.BLService.IBLService>, MobileApp.BLService.IBLService {
            
            public BLServiceClientChannel(System.ServiceModel.ClientBase<MobileApp.BLService.IBLService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPrices(byte[] image, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = image;
                System.IAsyncResult _result = base.BeginInvoke("GetPrices", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> EndGetPrices(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> _result = ((System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product>)(base.EndInvoke("GetPrices", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetShops(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetShops", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop> EndGetShops(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop> _result = ((System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Shop>)(base.EndInvoke("GetShops", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginPost(System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> products, MobileApp.BLService.Shop shop, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = products;
                _args[1] = shop;
                System.IAsyncResult _result = base.BeginInvoke("Post", _args, callback, asyncState);
                return _result;
            }
            
            public void EndPost(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Post", _args, result);
            }
            
            public System.IAsyncResult BeginTest(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Test", _args, callback, asyncState);
                return _result;
            }
            
            public string EndTest(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("Test", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSearch(string itemName, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = itemName;
                System.IAsyncResult _result = base.BeginInvoke("Search", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> EndSearch(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product> _result = ((System.Collections.ObjectModel.ObservableCollection<MobileApp.BLService.Product>)(base.EndInvoke("Search", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IBLService,
        }
    }
}
