//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClientTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAPIService")]
    public interface IAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPrices", ReplyAction="http://tempuri.org/IAPIService/GetPricesResponse")]
        ApiService.Product[] GetPrices(byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetPrices", ReplyAction="http://tempuri.org/IAPIService/GetPricesResponse")]
        System.Threading.Tasks.Task<ApiService.Product[]> GetPricesAsync(byte[] image);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetShops", ReplyAction="http://tempuri.org/IAPIService/GetShopsResponse")]
        ApiService.Shop[] GetShops();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetShops", ReplyAction="http://tempuri.org/IAPIService/GetShopsResponse")]
        System.Threading.Tasks.Task<ApiService.Shop[]> GetShopsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIServiceChannel : ConsoleClientTest.ServiceReference1.IAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceClient : System.ServiceModel.ClientBase<ConsoleClientTest.ServiceReference1.IAPIService>, ConsoleClientTest.ServiceReference1.IAPIService {
        
        public APIServiceClient() {
        }
        
        public APIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApiService.Product[] GetPrices(byte[] image) {
            return base.Channel.GetPrices(image);
        }
        
        public System.Threading.Tasks.Task<ApiService.Product[]> GetPricesAsync(byte[] image) {
            return base.Channel.GetPricesAsync(image);
        }
        
        public ApiService.Shop[] GetShops() {
            return base.Channel.GetShops();
        }
        
        public System.Threading.Tasks.Task<ApiService.Shop[]> GetShopsAsync() {
            return base.Channel.GetShopsAsync();
        }
    }
}
